---
title: "LNU Analysis"
author: "Ashley Grupenhoff"
date: "5/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/ashle/OneDrive/Documents/R/LNU_chaparral/LNU_chaparral")
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(vegan)
library(plyr)
library(brms)
library(rstan)
library(tidybayes)
library(bayesplot)
library(bayestestR)
library(emmeans)
library(viridis)


#run faster
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

```

## Input clean data
```{r data}
#raw
TOT_species_LNU <- read.csv("data/raw/TOT_species_LNU.csv")
subplot_species_LNU <- read.csv("data/raw/SubPlot_SPP_LNU.csv")
plot.description_LNU <- read.csv("data/raw/PlotDescription_LNU.csv")
severity_LNU <- read.csv("data/raw/Severity_LNU.csv")
GroundCover_LNU <- read.csv("data/raw/GroundCover_LNU.csv")
Mortality_LNU <- read.csv("data/raw/Mortality_LNU.csv")
SpeciesList <- read.csv("data/raw/SpeciesList_LNU.csv")

plot.description.short <- plot.description_LNU %>% 
  filter(Quad..if.applicable. == "") %>% 
  select(Location, plotid, num_burn, cool.warm_slope) %>% 
  dplyr::rename(PlotID = plotid)
severity_LNU_byplot <- severity_LNU %>% 
  group_by(PlotID) %>% 
  dplyr::summarise(Mean_diam_cm = mean(Mean_diam)) %>% 
  mutate(mean_diam_mm = Mean_diam_cm *10)
species.short <- SpeciesList %>% 
  select(spp, Lifeform, Native_nonnative, fac.obl) 

severity.plotdescription.LNU <- left_join(plot.description.short,severity_LNU_byplot, by= "PlotID")
severity.plotdescription.LNU$num_burn <- as.numeric(severity.plotdescription.LNU$num_burn)
#write.csv(severity.plotdescription.LNU,"data/clean/LNU_severity.plotdescription.csv" )

severity.plotdescription.LNU %>% 
  dplyr::count(num_burn, cool.warm_slope)


```

## Severity 

```{r severity}
  
sevdata <- ddply(severity.plotdescription.LNU, c("num_burn"),
                 summarise,
                 N = sum(!is.na(mean_diam_mm)),
                 mean_diam_mm_avg = mean(mean_diam_mm, na.rm=TRUE),
                 sd= sd(mean_diam_mm, na.rm = TRUE),
                 se = sd/sqrt(N)) 


ggplot(data=sevdata %>%  filter(num_burn != "2"), aes(x=as.factor(num_burn), y=mean_diam_mm_avg))+
                    geom_errorbar(aes(ymin=mean_diam_mm_avg-se, ymax=mean_diam_mm_avg+se), width=.1, size=.7)+
                    geom_line()+
                    geom_point(size=3, aes(colour=factor(num_burn)))+
                    scale_colour_viridis_d()+
                     xlab("Fire frequency")+
                     ylab("Fire Severity")+
                    theme_bw()+
                   theme(legend.title = element_blank(),
                           axis.text = element_text(size=15),
                            text = element_text(size = 16),
                          panel.grid = element_blank())
ggsave(file="figures/sev~freq.svg", width = 4.5, height = 3)
ggsave(file="figures/sev~freq.png", width = 4.5, height = 3)





#LINEAR MODEL
qqnorm(severity.plotdescription.LNU$mean_diam_mm, pch = 1, frame = FALSE)
qqline(severity.plotdescription.LNU$mean_diam_mm, col = "steelblue", lwd = 2)

m.sev <- lm(num_burn ~ mean_diam_mm ,
                 data = severity.plotdescription.LNU, REML = F)
summary(m.sev)
coef(summary(m.nativeRich))
plot(m.sev)

```


# Subplot Native & Nonnative


```{r}

LNU_subplot_native <- read.csv("data/clean/LNU_subplot_native_long.csv" )
LNU_sub_native_wide <- read.csv("data/clean/LNU_subplot_native_wide.csv")

LNU_subplot_nonnative <- read.csv("data/clean/LNU_subplot_nonnative_long.csv" )
LNU_sub_nonnative_wide <- read.csv("data/clean/LNU_subplot_nonnative_wide.csv")

 

```

# NMDS

```{r}
library(vegan)

load(file = "data/clean/LNU_subplot_wide_species.RData")

#make community matrix on which to base ordination
LNUspecies = LNU_subplot_wide %>% select(!PlotID)
#columns that contain descriptive data
LNUplot_ord = LNU_subplot_wide %>% 
  select(PlotID) 
LNUplot_env <- left_join(LNUplot_ord, plot.description.short %>% distinct(), by = "PlotID")

set.seed(123) #reproduce same results
NMDS <- metaMDS(LNUspecies, distance="bray", k=2) #no transformation of species data is made here prior to bray curtis dissimilarities being calculated. 
NMDS

#env.fit
nmds_plot <- cbind(NMDS$point, LNUplot_env)
nmds_species <- left_join(cbind(as.data.frame(NMDS$species), 
                                as.data.frame(row.names(as.data.frame(NMDS$species)))), 
                               # %>% rename(spp = "row.names(as.data.frame(NMDS$species))")
                                species.short, by = c("row.names(as.data.frame(NMDS$species))"="spp" ))

nmds_plot$num_burn <- as.factor(nmds_plot$num_burn)

ggplot(nmds_plot %>% filter(num_burn != "7"), aes(x=MDS1, y=MDS2))+
  geom_point(size = 4, aes(x=MDS1, y=MDS2, color = num_burn))+
  #geom_point(data= nmds_species, size = 1.8, alpha = 0.5, aes(x=MDS1, y=MDS2, 
  #                                               shape = Native_nonnative))
  stat_ellipse(aes(x=MDS1, y=MDS2, color = num_burn))+
  scale_color_viridis_d()+
  guides(col=guide_legend("Fire Frequency"))+
  theme(axis.text = element_text(size=15),
        text = element_text(size = 16),
        panel.grid = element_blank(),
        legend.text = element_text(size=12),
        legend.title = element_text(size=11))
ggsave(file="figures/NMDS.svg", width = 5, height = 3)
ggsave(file="figures/NMDS.png", width = 5, height = 3)



```



# Richness


```{r Richness, echo=FALSE}
#calculate richness

LNU_sub_nonnative_wide <- read.csv("data/clean/LNU_subplot_nonnative_wide.csv")
LNU_sub_native_wide <- read.csv("data/clean/LNU_subplot_native_wide.csv")
#sum up the number of non-zero entries per row 
#first column ignored ([,-1]) since this is the site name, not species count
LNU_richness_nonnative <- ddply(LNU_sub_nonnative_wide,~plot_yr_quad,function(x) {
  data.frame(NONNATIVE_RICHNESS=sum(x[-2]>0.0))})

LNU_richness_native <- ddply(LNU_sub_native_wide,~plot_yr_quad,function(x) {
  data.frame(NATIVE_RICHNESS=sum(x[-2]>0.0))})

LNU_richness <- left_join(LNU_richness_native, LNU_richness_nonnative, by="plot_yr_quad")
LNU_richness <- LNU_richness %>% 
  pivot_longer(!plot_yr_quad,names_to = "native.nonnative",
               values_to = "richness") %>% 
  separate(plot_yr_quad, c("plot_year", "quad"), sep=" ") %>% 
  separate(plot_year, c("PlotID", "year"), sep="_") 
LNU_richness <- left_join(LNU_richness, severity.plotdescription.LNU, by="PlotID")
LNU_richness$num_burn <- as.factor(LNU_richness$num_burn)
str(LNU_richness)

nativeRich <- LNU_richness %>% 
  filter(native.nonnative == "NATIVE_RICHNESS") %>% 
  filter(num_burn != "7")
nonnativeRich <- LNU_richness %>% 
  filter(native.nonnative == "NONNATIVE_RICHNESS")%>% 
  filter(num_burn != "7")

#write.csv(LNU_richness, "data/clean/LNU_subplot_RICHNESS.csv")


##BAYESIAN
#repeated measures looking at richness based on different fire frequencies 
summary(LNU_richness)
plot(richness ~ num_burn, data=nativeRich)
plot(richness ~ num_burn, data=nonnativeRich)

#gaussian based model seems better than gamma 
n.natRich <- brm(richness ~ num_burn, data = nativeRich,
                 prior=c(set_prior("normal(0,50)", class= "b")), 
                 cores=4,
                 file = "models/nativeRich")
summary(n.natRich)
contrasts(nativeRich$num_burn)
hist(resid(n.natRich))
pp_check(n.natRich)

ems <- emmeans(n.natRich, specs= pairwise ~num_burn)
summary(pairs(ems), point.est = mean)

plot(conditional_effects(n.natRich))
native.rich.model <- n.natRich %>% 
  emmeans( ~num_burn) %>% 
  gather_emmeans_draws() %>% 
  mutate(native_richness = .value)
native.rich.model

#now plot!!
native_rich_plot <- ggplot(data = native.rich.model,
                           aes(x = num_burn, y=native_richness, fill = native_richness))+
  stat_halfeye()+
  labs(x = expression(italic("Fire Frequency")),
       y = "Native Richness") +
  scale_fill_viridis(discrete = TRUE)+
  theme(panel.grid   = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0, size = 13),
        axis.text.x = element_text(size = 10),
        legend.title = element_blank())
native_rich_plot

#gaussian based model seems better than gamma 
n.nonnatRich <- brm(richness ~ num_burn, data = nonnativeRich,
                 prior=c(set_prior("normal(0,50)", class= "b")), 
                 cores=4,
                 file = "nonnativeRich")
summary(n.nonnatRich)
contrasts(nonnativeRich$num_burn)
hist(resid(n.nonnatRich))
pp_check(n.nonnatRich)

plot(conditional_effects(n.nonnatRich))

emmeans(n.nonnatRich, specs= pairwise ~num_burn)

nonnative.rich.model <- n.nonnatRich %>% 
  emmeans( ~num_burn) %>% 
  gather_emmeans_draws() %>% 
  mutate(nonnative_richness = .value)
nonnative.rich.model

#now plot!!
nonnative_rich_plot <- ggplot(data = nonnative.rich.model,
                           aes(x = num_burn, y=nonnative_richness, fill = nonnative_richness))+
  stat_halfeye()+
  labs(x = expression(italic("Fire Frequency")),
       y = "Nonnative Richness") +
  scale_fill_viridis(discrete = TRUE)+
  theme(panel.grid   = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0, size = 13),
        axis.text.x = element_text(size = 10),
        legend.title = element_blank())
nonnative_rich_plot


            
```

# Shannon Diversity

```{r Shannon}

library(sjPlot)

######SHANNON DIVERSITY
#sum up the number of non-zero entries per row 
#first column ignored ([,-1]) since this is the site name, not species count
LNU_shan_nonnative <- ddply(LNU_sub_nonnative_wide,~plot_yr_quad,function(x) {
  data.frame(NONNATIVE_shanDiv=diversity(x[-2], index="shannon"))})

LNU_shan_native <- ddply(LNU_sub_native_wide,~plot_yr_quad,function(x) {
  data.frame(NATIVE_shanDiv=diversity(x[-2], index="shannon"))})

LNU_shanDiv <- left_join(LNU_shan_native, LNU_shan_nonnative, by="plot_yr_quad")
LNU_shanDiv <- LNU_shanDiv %>% 
  pivot_longer(!plot_yr_quad,names_to = "native.nonnative",
               values_to = "shanDiv") %>% 
  separate(plot_yr_quad, c("plot_year", "quad"), sep=" ") %>% 
  separate(plot_year, c("PlotID", "year"), sep="_") 

LNU_shanDiv <- left_join(LNU_shanDiv,severity.plotdescription.LNU, by="PlotID")
LNU_shanDiv$num_burn <- as.factor(LNU_shanDiv$num_burn)
str(LNU_shanDiv)
nativeShan <- LNU_shanDiv %>% 
  filter(native.nonnative == "NATIVE_shanDiv") %>% 
  filter(num_burn != "7")
nonnativeShan <- LNU_shanDiv %>% 
  filter(native.nonnative == "NONNATIVE_shanDiv") %>% 
  filter(num_burn != "7")

#write.csv(LNU_shanDiv, "data/clean/LNU_subplot_shanDiv.csv")


#Bayesian model

plot(shanDiv ~ num_burn, data=nativeShan)
plot(shanDiv ~ num_burn, data=nonnativeShan)


#gaussian based model seems better than gamma 
str(nativeShan)
hist(nativeShan$shanDiv)
n.natShan <- brm(shanDiv ~ num_burn, 
                 data = nativeShan,
                 prior=c(set_prior("normal(0,2)", class= "b")), 
                 cores=4,
                 file = "models/nativeShan")
summary(n.natShan)
hist(resid(n.natShan))
pp_check(n.natShan)


plot(conditional_effects(n.natShan))

emmeans(n.natShan, specs= pairwise ~num_burn)

natShan.model <- n.natShan %>% 
  emmeans( ~num_burn) %>% 
  gather_emmeans_draws() %>% 
  mutate(native_shannon = .value)
natShan.model

#now plot!!
natShan_plot <- ggplot(data = natShan.model,
                           aes(x = num_burn, y=native_shannon, fill = native_shannon))+
  stat_halfeye()+
  labs(x = expression(italic("Fire Frequency")),
       y = "Native Shannon Diversity") +
  scale_fill_viridis(discrete = TRUE)+
  theme(panel.grid   = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0, size = 13),
        axis.text.x = element_text(size = 10),
        legend.title = element_blank())
natShan_plot


hdi(n.natShan)
#get adjusted means
warp_em <- emmeans::emmeans(n.natShan, ~ num_burn)
warp_em
#get all possible constrasts
cont <- contrast(warp_em, "tukey")
cont
#get posterior draws
con_posterior <- gather_emmeans_draws(cont)
#plot
ggplot(con_posterior,
       aes(y = contrast, x = .value)) +
  geom_halfeyeh() +
  geom_vline(xintercept = 0, color = "red", lty = 2)
emmip(n.natShan,  ~ num_burn, CIs = TRUE, cov.reduce = range)



#gaussian based model seems better than gamma 
str(nonnativeShan)
n.nonnatShan <- brm(shanDiv ~ num_burn, data = nonnativeShan,
                 prior=c(set_prior("normal(0,2)", class= "b")), 
                 cores=4)
summary(n.nonnatShan)
hist(resid(n.nonnatShan))
pp_check(n.nonnatShan)
plot(n.nonnatShan)

plot(conditional_effects(n.nonnatShan))

emmeans(n.nonnatShan, specs= pairwise ~num_burn)

nonnatShan.model <- n.nonnatShan %>% 
  emmeans( ~num_burn) %>% 
  gather_emmeans_draws() %>% 
  mutate(nonnative_shannon = .value)
nonnatShan.model

#now plot!!
nonnatShan_plot <- ggplot(data = nonnatShan.model,
                           aes(x = num_burn, y=nonnative_shannon, fill = nonnative_shannon))+
  stat_halfeye()+
  labs(x = expression(italic("Fire Frequency")),
       y = "Nonnative Shannon Diversity") +
  scale_fill_viridis(discrete = TRUE)+
  theme(panel.grid   = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_text(hjust = 0, size = 13),
        axis.text.x = element_text(size = 10),
        legend.title = element_blank())
nonnatShan_plot

hypnonNatShan = hypothesis(n.nonnatShan,
                        hypothesis = c("Intercept=0",
                                       "Intercept+num_burn2=0",
                                       "Intercept+num_burn3=0",
                                       "Intercept+num_burn4=0",
                                       "Intercept+num_burn5=0"))
toplot = hypnonNatShan$samples
toplot
names(toplot) = c("1 Fire","2 Fire","3 Fires","4 Fires","5 Fires")
mcmc_intervals(toplot, prob_outer = .95, prob=.68)+
xlab("Nonnative Shannon Diversity")



```
# Seedling and resprout density and cover data
This was cleaned up in lnu_clean file

```{r seedling resprout data}


shrub_density_wide <- read.csv("data/clean/LNU_subplot_shrub_density_wide.csv")
shrub_density_long <- read.csv("data/clean/LNU_subplot_shrub_density_long.csv")

```


# Seedling Density

```{r Seedling Density }

library(lattice)
library(MASS)
library(lmtest)
library(pscl)
library(ggeffects)

#####DENSITY
str(shrub_density_long)
shrub_density_long <- left_join(shrub_density_long, plot.description.short, by="PlotID")
shrub_density_long <- left_join(shrub_density_long, species.short, by ="spp")


plot(density_ha ~ as.factor(num_burn), data=shrub_density_long)
#check numbe of 0s
100*sum(shrub_density_long$density_ha == 0)/nrow(shrub_density_long)
#88% are 0s lolllll

#zero inflated model for obligate seeders only
shrub_density_OBLS <- shrub_density_long %>%
  filter(seed.resp == "SEEDLING") %>% 
  filter(fac.obl == "OBL-S") %>% 
  filter(spp != "ACMGLA") 
unique(shrub_density_OBLS$spp)

shrub_density_OBLS$num_burn <- as.factor(shrub_density_OBLS$num_burn)

hist(shrub_density_OBLS$density_ha)
n.shrubDensityOBL <- brm(data = shrub_density_OBLS,
                      density_ha ~ num_burn,
                       family = zero_inflated_negbinomial(),
                      prior = c(prior(normal(0, 10), class = Intercept),
                                prior(beta(2, 2), class = zi)),
                 cores=4,
                 file = "models/shrubDensityOBL")

summary(n.shrubDensityOBL)
pp_check(n.shrubDensityOBL)
conditional_effects(n.shrubDensityOBL)

OBLS.model <- n.shrubDensityOBL%>% 
  emmeans( ~num_burn) %>% 
  gather_emmeans_draws() %>% 
  mutate(density_ha = .value)
OBLS.model

M1 <- zeroinfl(density_ha ~ as.factor(num_burn),
               dist = "negbin",
          data = shrub_density_OBLS)
summary(M1)
#check for over/underdispersion
E2 <- resid(M1, type = "pearson")
N <- nrow(shrub_density_long)
p <- length(coef(M1))
sum(E2^2)/(N-p)
#.095 looks good

mydf <- ggpredict(M1, type= "zi_random", terms = "num_burn") 

ggplot(mydf, aes(as.factor(x), predicted))+
  geom_point(size=3,position = position_dodge(.1), aes(color=as.factor(x))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
              position = position_dodge(.1),
              width=.1, size=.3) +
  scale_colour_viridis_d()+
  xlab("Fire frequency")+
  ylab("Obligate Seedling density/Ha")+
  theme_bw()+
  theme(legend.position = "none",
  axis.text = element_text(size=12),
  text = element_text(size = 14),
  panel.grid = element_blank())
ggsave(file="figures/obl_seed_predicted.svg", width = 4.5, height = 3.5)
ggsave(file="figures/obl_seed_predicted.png", width = 4.5, height = 3.5)


#zero inflated model for facultative seeders only
shrub_density_FAC <- shrub_density_long %>%
  filter(seed.resp == "SEEDLING") %>% 
  filter(fac.obl == "FAC") %>% 
  filter(spp != "MIMAUR") %>% 
    filter(spp != "HOLDIS") 
unique(shrub_density_FAC$spp)

M2 <- zeroinfl(density_ha ~ as.factor(num_burn),
               dist = "negbin",
          data = shrub_density_FAC)
summary(M2)
#check for over/underdispersion
E3 <- resid(M2, type = "pearson")
N <- nrow(shrub_density_long)
p <- length(coef(M2))
sum(E3^2)/(N-p)
#.286 nooo 

mydf2 <- ggpredict(M2, type= "zi_random", terms = "num_burn") 
mydf2
ggplot(mydf2, aes(as.factor(x), predicted))+
  geom_point(size=3,position = position_dodge(.1), aes(color=as.factor(x))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
              position = position_dodge(.1),
              width=.1, size=.3) +
  scale_colour_viridis_d()+
  xlab("Fire frequency")+
  ylab("Facultative Seedling density/Ha")+
  theme_bw()+
  theme(legend.position = "none",
  axis.text = element_text(size=12),
  text = element_text(size = 14),
  panel.grid = element_blank())
ggsave(file="figures/fac_seed_predicted.svg", width = 4.5, height = 3.5)
ggsave(file="figures/fac_seed_predicted.png", width = 4.5, height = 3.5)



#zero inflated model for ADFA only
ADFA_density_FAC <- shrub_density_long %>%
  filter(seed.resp == "SEEDLING") %>% 
  filter(fac.obl == "FAC") %>% 
  filter(spp == "ADFA") 
unique(ADFA_density_FAC$spp)

M2 <- zeroinfl(density_ha ~ as.factor(num_burn),
               dist = "negbin",
          data = ADFA_density_FAC)
summary(M2)
#check for over/underdispersion
E3 <- resid(M2, type = "pearson")
N <- nrow(shrub_density_long)
p <- length(coef(M2))
sum(E3^2)/(N-p)
#.286 nooo 

mydf2 <- ggpredict(M2, type= "zi_random", terms = "num_burn") 
mydf2
ggplot(mydf2, aes(as.factor(x), predicted))+
  geom_point(size=3,position = position_dodge(.1), aes(color=as.factor(x))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
              position = position_dodge(.1),
              width=.1, size=.3) +
  scale_colour_viridis_d()+
  xlab("Fire frequency")+
  ylab("ADFA Seedling density/Ha")+
  theme_bw()+
  theme(legend.position = "none",
  axis.text = element_text(size=12),
  text = element_text(size = 14),
  panel.grid = element_blank())
ggsave(file="figures/ADFA_seed_predicted.svg", width = 4.5, height = 3.5)
ggsave(file="figures/ADFA_seed_predicted.png", width = 4.5, height = 3.5)


#zero inflated model for ERCAL only
ERICAL_density_FAC <- shrub_density_long %>%
  filter(seed.resp == "SEEDLING") %>% 
  filter(fac.obl == "FAC") %>% 
  filter(spp == "ERICAL") 
unique(ERICAL_density_FAC$spp)

M2 <- zeroinfl(density_ha ~ as.factor(num_burn),
               dist = "negbin",
          data = ERICAL_density_FAC)
summary(M2)
#check for over/underdispersion
E3 <- resid(M2, type = "pearson")
N <- nrow(shrub_density_long)
p <- length(coef(M2))
sum(E3^2)/(N-p)
#.286 nooo 

mydf2 <- ggpredict(M2, type= "zi_random", terms = "num_burn") 
mydf2
ggplot(mydf2, aes(as.factor(x), predicted))+
  geom_point(size=3,position = position_dodge(.1), aes(color=as.factor(x))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
              position = position_dodge(.1),
              width=.1, size=.3) +
  scale_colour_viridis_d()+
  xlab("Fire frequency")+
  ylab("ERICAL Seedling density/Ha")+
  theme_bw()+
  theme(legend.position = "none",
  axis.text = element_text(size=12),
  text = element_text(size = 14),
  panel.grid = element_blank())
ggsave(file="figures/ERICAL_seed_predicted.svg", width = 4.5, height = 3.5)
ggsave(file="figures/ERICAL_seed_predicted.png", width = 4.5, height = 3.5)

#zero inflated model for LEPCAL only
LEPCAL_density_FAC <- shrub_density_long %>%
  filter(seed.resp == "SEEDLING") %>% 
  filter(fac.obl == "FAC") %>% 
  filter(spp == "LEPCAL") 
unique(LEPCAL_density_FAC$spp)

M2 <- zeroinfl(density_ha ~ as.factor(num_burn),
               dist = "negbin",
          data = LEPCAL_density_FAC)
summary(M2)
#check for over/underdispersion
E3 <- resid(M2, type = "pearson")
N <- nrow(shrub_density_long)
p <- length(coef(M2))
sum(E3^2)/(N-p)
#.286 nooo 

mydf2 <- ggpredict(M2, type= "zi_random", terms = "num_burn") 
mydf2
ggplot(mydf2, aes(as.factor(x), predicted))+
  geom_point(size=3,position = position_dodge(.1), aes(color=as.factor(x))) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high),
              position = position_dodge(.1),
              width=.1, size=.3) +
  scale_colour_viridis_d()+
  xlab("Fire frequency")+
  ylab("LEPCAL Seedling density/Ha")+
  theme_bw()+
  theme(legend.position = "none",
  axis.text = element_text(size=12),
  text = element_text(size = 14),
  panel.grid = element_blank())
ggsave(file="figures/LEPCAL_seed_predicted.svg", width = 4.5, height = 3.5)
ggsave(file="figures/LEPCAL_seed_predicted.png", width = 4.5, height = 3.5)


```



```{r}

str(shrub_cover)
shrub_cover <- left_join(shrub_cover, severity.plotdescription.LNU, by="PlotID")
shrub_cover <- left_join(shrub_cover, species.short, by ="spp")
shrub_cover$num_burn <- as.numeric(shrub_cover$num_burn)
shrub_cover$cover <- as.numeric(shrub_cover$cover)

shrub_cover %>%
  filter(seed.resprout == "SEEDLING") %>% 
  filter(spp == "ERICAL"|
           spp == "ADFA" |
           spp == "LEPCAL"|
           spp == "CEACUN"|
           spp == "CEAOLI"|
           spp == "ARCMAN") %>%
ggplot(aes(x=num_burn, y=cover, col = spp))+
    geom_smooth(method="lm", se=F)

shrub_cover %>%
  filter(seed.resprout == "RESPROUT") %>% 
  
ggplot(aes(x=num_burn, y=cover, col = spp))+
    geom_smooth(method="lm", se=F)

    
    
    
    sh_count <- left_join(sh_count, plot.description.short, by="PlotID")
   sh_count <- left_join(sh_count, species.short, by ="spp")
    sh_count$num_burn <- as.numeric(sh_count$num_burn)
    sh_count$density <- as.numeric(sh_count$density)
    
    ggplot(data=sh_count, aes(x=num_burn, y=density, colour=spp))+
      geom_smooth(method = "lm")
    
    
```















